version: '3.9'

services:
  app:
    build: .
    container_name: cv_creator_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama
    command: >
      bash -c "pip install -r requirements.txt &&
               python src/main.py"

  ollama:
    image: ollama/ollama
    container_name: ollama_llm
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
